Comment Author Name and Time
pycontribs/jira pull request #1001
Opened 2021-02-24 10:27 UTC by pperum002c

Just updated in comments section, additional field details like author name and commented time.

2021-02-25 11:49 UTC, pperum002c reviewed
Added Comment Attributes

2021-04-04 23:51 UTC, studioj requested changes
looks like the maintainers want to have the ci system back up and running before agreeing to any new merges.

if you want to contribute to get yr pr through have a look here => https://github.com/pycontribs/jira/issues/896

Maybe since its documentation only they can have it merged.
BTW I'm not a maintainer :-)

2021-04-04 23:51 UTC, studioj commented on docs/examples.rst
> +Get commented author name and time if you know its ID::
```suggestion
Get comment author name and comment creation timestamp if you know its ID::
```

2021-05-03 09:50 UTC, ssbarnea approved these changes

2021-05-07 21:36 UTC, studioj approved these changes

2021-05-07 21:37 UTC, studioj commented
@ssbarnea  seems this can be merged

2021-05-12 19:44 UTC, ssbarnea approved these changes

2021-05-12 19:44 UTC, merged