(fix): Adding accountId parameter on user
pycontribs/jira pull request #1007
Opened 2021-03-16 14:33 UTC by LKhoe

Hello, I found a problem in user function and fixed it.
See you.

2021-04-09 20:06 UTC, russoz commented on README.rst
> +It's just and fix for the original lib
This text does not add much to the end user, IMO.

2021-04-09 20:10 UTC, russoz commented on jira/client.py
> +        params = {'accountId': id}
The "accountId" change happened a couple of years ago, but I am not sure (not that I looked for  it) what is the backward compatibility policy of this package.

So, it should be interesting not to force that upon all users.

2021-04-09 20:11 UTC, russoz commented on setup.cfg
> +name = jira_333
why?

2021-04-09 20:12 UTC, russoz commented on setup.py
> +    setuptools.setup(version='3.4.0')
Why are we pinning down a specific version here?

2021-05-02 12:42 UTC, adehad requested changes

2021-05-02 12:42 UTC, adehad commented on jira/client.py
> +    def get_changelogs_from_issue(self, issueID_or_key):
these functions do not follow the style of the rest of the class.

Here we could use `self._get_json()` with the default `base` argument, the next function can use the argument `base=AGILE_BASE_URL`

2021-05-02 12:59 UTC, closed without merging