add PermissionScheme Resource
pycontribs/jira pull request #1139
Opened 2021-09-02 07:19 UTC by Steffen223

make PermissionScheme Resource also available when using pycontribs/jira.
tox lint passed. But I had issues with my environment using tox tests. Using this branch in a our script worked successful

2021-09-17 22:24 UTC, adehad requested changes
looking good ! Tests can be a bit tricky as you need to setup docker, but if you can try something locally feel free to add a test file to the `test/resources/` folder and we can see how it runs on the CI

2021-09-17 22:24 UTC, adehad commented on jira/client.py
> +        """
Let's use the Google style docstring 

```suggestion

        Args:
            project (str): ID or key of the project to get the permissionscheme for

        Returns:
        PermissionScheme: The permission scheme
        """
```

2021-09-17 22:24 UTC, adehad commented on jira/client.py
> +    def project_permissionscheme(self, project):
```suggestion
    def project_permissionscheme(self, project: str):
```

2021-09-17 22:24 UTC, adehad commented on jira/resources.py
> +
```suggestion
        self.raw: Dict[str, Any] = cast(Dict[str, Any], self.raw)
```

2021-09-23 11:51 UTC, Steffen223 commented
Hello @adehad , a test has been added to https://github.com/Steffen223/jira/blob/master/tests/resources/test_project.py#L204

2021-09-23 12:12 UTC, adehad commented
Test failure is unrelated to this, seems like we need to reconfigure something on our github actions end. Will try and sort this out and then re-run the jobs.

2021-09-24 08:29 UTC, adehad commented
Looks like a few linting error popped up could you run `tox -e lint` ?
Can you also first rebasing / merge master back in? As we just merged in an update to our lint

2021-09-28 09:49 UTC, Steffen223 commented
Hello @adehad , I linted, updated and merged from master.

2021-09-28 13:50 UTC, adehad approved these changes

2021-09-28 13:50 UTC, merged

2021-09-28 13:51 UTC, adehad commented
Awesome, thank you for your contribution !