Allow disabling searching for user on assign_issue
pycontribs/jira pull request #1301
Opened 2022-03-03 16:21 UTC by tvarney

This adds a parameter to the `_get_user_id()` method which allows for
selectively disabling the search for the user that said method performs.
This allows for code to perform it's own user search prior to calling
methods which use this method (e.g. `assign_issue`). This fixes an issue
where the search would return the wrong user due to the ordering of
users, and prevents the code from issuing duplicate search calls to the
Jira server when the user has already done so.

Closes #1284

2022-03-05 22:30 UTC, adehad commented
Thanks for this.

Could I ask you to check if the proposal in #1145 would work for you? I think it may be an elegant way to handle this case.

If not I have another idea to run by you, what are you thoughts on making this a state variable for the client? 
Perhaps the use might look like:

```python
jira_client = ...
jira_client.disable_internal_user_lookup()
jira_client.assign_issue(...)
jira_client.enable_internal_user_lookup()

# or perhaps with a context manager to be more explicit:
with disable_internal_user_lookup(jira_client):
    jira_client.assign_issue(...)
```

I can imagine that if you already know the user by key/id it may make sense to temporarily disable this.

Another option would be for us to remove the `@translate_resource_args` and handle it internally inside the function instead, so someone can pass in a `User` object, but would require a change in the use for someone to benefit from the change.

2022-03-10 17:09 UTC, tvarney commented
The proposal in #1145 would fix the issue, but my preference would be to still have a way to disable internal searching entirely; e.g. for bulk editing of tickets where we already have an exact username it makes more sense to not attempt to search the user on every `assign_issue`. In that vein I've added your suggestion for a context manager because it seems like the cleanest way of handling this.

2022-03-10 20:03 UTC, adehad requested changes

2022-03-16 18:53 UTC, tvarney commented on jira/client.py
> +            self._internal_user_lookup = True
Addressing your first comment, that was mostly just that I forgot you can `yield` None like that, so I added a 'simple' value. Fixed that up.

For comment 2, I went ahead and added a docstring but I'm not sure what level of detail is appropriate (or if I did the `py:meth` annotations correctly). Let me know if the language needs tweaking.

Finally on comment 3, I'm having issues actually running the tests - I've tried on both Windows with Docker for Desktop and on Linux, and while the issue is different I can't seem to get the tests to actually run on either system. I _think_ I've added a test, but I'm not actually familiar with the testing framework being used.

2022-03-16 22:44 UTC, adehad commented on jira/client.py
> +            self._internal_user_lookup = True
Hi, no worries the tests do require some setup. But without know what error message you are seeing it is hard to know what to suggest. But feel free to rely on the CI we have running on this pull request automatically:
Click the "details" link next to a failing step to see why it failed:
![image](https://user-images.githubusercontent.com/26027314/158703399-80cb226b-8edc-4f85-bfc3-947f84eb760d.png)
(https://github.com/pycontribs/jira/runs/5575285913?check_suite_focus=true#step:8:70 )

2022-03-16 22:45 UTC, adehad commented on jira/client.py
> +            self._internal_user_lookup = True
You can also see the docs generated for this pull request here:

https://jira--1301.org.readthedocs.build/

2022-03-16 22:51 UTC, adehad requested changes

2022-03-16 22:51 UTC, adehad commented on jira/client.py
> +        self._internal_user_lookup = False
```suggestion
        :Example:

            .. code-block:: python
                # Bulk assigning tickets to a know user, saving internal lookup time
                my_user_id = "user_x"
                issue_list = ... # some list of issues
                with jira_client.disable_internal_user_lookup():
                    for issue in issue_list:
                        jira_client.assign_issue(issue, my_user_id )

        Return:
            contextlib._GeneratorContextManager
        """
        self._internal_user_lookup = False
```

You can checkout your function generated docs here:
https://jira--1301.org.readthedocs.build/api.html#jira.client.JIRA.disable_internal_user_lookup - you used the right syntax for cross-referencing a method.

2022-03-16 22:51 UTC, adehad commented on tests/test_client.py
> +        result = cl_normal._get_user_id()
```suggestion
        result = cl_normal._get_user_id(username)
```

2022-04-05 21:09 UTC, tvarney commented on jira/client.py
> +            self._internal_user_lookup = True
I think the main issues pointed out here have been addressed - not sure what's going on with the builds though :disappointed:

2022-04-08 15:00 UTC, adehad commented
@tvarney I think if you merge in/rebase the latest master it might fixup some of these errors

2022-08-06 20:41 UTC, adehad commented
just a nudge here @tvarney, would be great to include this in

2023-02-09 20:46 UTC, studioj commented
@tvarney Thanks for the contribtion, could you still follow up. If not also ok, though it would be nice if you could.
Kr

2024-06-26 14:31 UTC, dimitarOnGithub commented
Hi everyone, I know this is a bit old, apologies for the notification spam.

I wonder if a better solution here might be to simply remove the user lookup entirely ,or at least rework the `_get_user_id` method; currently, it's operating off the assumption that the first returned user would be one that the invoking code meant in first place, which is not necessarily the case.

Removing the user lookup from the methods that perform it (assign_issue, add_watcher, remove_watcher) should achieve the same, unless I'm missing something crucial. If no user is matched on `accountId` (for cloud) or `name` (for hosted), the library itself throws JIRAError.

2025-03-31 13:06 UTC, closed without merging