Remove setup_requires for setuptools_scm_git_archive
pycontribs/jira pull request #1384
Opened 2022-05-25 06:33 UTC by fdebrabander

This dependency is not needed.

The documentation at https://github.com/Changaco/setuptools_scm_git_archive
states that there are two files needed for this to work .git_archival.txt and
.gitattributes. Both files are missing in this repository.

See also https://github.com/pycontribs/jira/discussions/1365

2022-06-25 23:42 UTC, studioj approved these changes

2022-07-11 09:03 UTC, ssbarnea requested changes
If you fix this, please ensure that you require setuptools_scm > 7 like it is described in the link you provided. You should also check that pip can install git archives made by github, so you might have to add the missing files.

2022-07-14 17:34 UTC, studioj requested changes

2022-07-14 17:34 UTC, studioj commented on setup.cfg
>      setuptools_scm >= 1.15.0
as @ssbarnea says maybe bump the required version for setuptools_scm

2022-08-01 19:35 UTC, adehad commented on setup.cfg
>      setuptools_scm >= 1.15.0
```suggestion
    setuptools_scm >= 7.0.0
```

2022-08-01 21:28 UTC, adehad commented
man it's actually a mess, I'll make a PR to move to a single `pyproject.toml`, too much legacy stuff kicking about

2022-09-06 10:29 UTC, adehad commented
Refer to #1443 
Thanks for initiating this @fdebrabander, you are a co-author on the merged commit, and thank you for your contribution !

2022-09-06 10:29 UTC, closed without merging