(#1437) derive attachment fname from BufferedReader object
pycontribs/jira pull request #1438
Opened 2022-07-28 15:37 UTC by mtripoli

Offering a fix for #1437.

2022-07-30 22:43 UTC, adehad requested changes
Thanks @mtripoli, change looks good to me I think
test failure isn't related to this, but could I ask if you can add a test case here:
https://github.com/pycontribs/jira/blob/main/tests/resources/test_attachment.py

Can be a very simple one we we just include the first argument and if no exception is raised and the attachment is found we are all good. Hopefully the existing cases are sufficient to help you crack on, if not let me know and I can write up a test case

2022-07-31 00:05 UTC, mtripoli commented
@adehad , done. I totally missed the tests/resources dir otherwise I would have provided the coverage for the change on the first go.

2022-07-31 16:19 UTC, adehad requested changes

2022-07-31 16:19 UTC, adehad commented on tests/resources/test_attachment.py
> +        #
excellent test case, however, let's put this into a new method, the test name doesn't make sense here

We don't need to add a number to the tests so just something like:


```suggestion
    def test_add_attachment_without_filename(self):
        issue = self.jira.issue(self.issue_1)
        attachment_no_filename_specified = self.jira.add_attachment(
            issue=issue,
            attachment=TEST_ATTACH_PATH,
            filename=None,
        )
        new_attachment = self.jira.attachment(attachment_no_filename_specified.id)
        msg = f"attachment, no filename specified {new_attachment.__dict__} of issue {issue}"
        assert new_attachment.filename == Path(TEST_ATTACH_PATH).name, msg

    def test_2_add_remove_attachment_using_filename(self):
        issue = self.jira.issue(self.issue_1)
```

(I've also moved away from the self.assert methods, one day we will clean out the legacy unittest syntax)

2022-07-31 16:20 UTC, adehad commented
> @adehad , done. I totally missed the tests/resources dir otherwise I would have provided the coverage for the change on the first go.

No problem at all, the tests are definitely hard to understand for new contributors, its on my list to update the contributing guide to clarify things

2022-08-01 09:08 UTC, adehad approved these changes
Awesome, thanks for this !

2022-08-01 09:10 UTC, merged