add createmeta_84age implementation
pycontribs/jira pull request #1503
Opened 2022-09-20 05:22 UTC by dshvedchenko

this is draft for implementation of createmeta required according to changes causing #1462

2022-09-30 15:14 UTC, adehad requested changes
Great start !!
Made some comments, it would also be great if we can get some tests in, let me know if you need help on that front.
I would have a look at the `tests/resources/` folder

2022-10-17 14:12 UTC, Ry-DS commented on jira/client.py
> +            DeprecationWarning("The `createmeta` is deprecated, use createmeta_v2")
@dshvedchenko sorry to hear you're affected 😔 hope all is well for you! If you give write access to your fork, I'm more than happy to finish the job :)

2022-11-08 10:49 UTC, dshvedchenko commented
need suggestions on how to automate tests for this.
current ci server is still 8.17 so can not be used to test on 9.0.0 jira branch

2022-11-09 09:38 UTC, dshvedchenko commented on jira/client.py
> +            projectKey = projectKeys
I've fixed issueType id and Name and projected mandatoriness.

I also agree that reconstruct is not a best way, 

but this approach enables a lot of old client code to be in touch, and allow it to work with new server with only library version upgrade.

of course we need to provide dedicated method for 8.4.0+eon . btw it was my itial commit adding "prominent" :) createmeta_v2 method :)

2022-12-22 14:46 UTC, dshvedchenko commented on jira/client.py
> +            projectKey = projectKeys
remove dedicated method

2022-12-22 14:46 UTC, dshvedchenko commented
can we have a progress on this or on #1527 PRs

2023-01-29 17:36 UTC, adehad commented
Thank you again for all the effort on this PR @dshvedchenko, sorry that we went with the alternative PR this time. Hope you can contribute again in the future !

2023-01-29 17:36 UTC, closed without merging