adding sprint goal
pycontribs/jira pull request #1586
Opened 2023-01-08 15:04 UTC by mohit2152sharma

The method `update_sprint` doesn't allow to update the sprint goal, as it is not included in method's parameter. Simply adding `goal` into function's argument, just like other arguments (e.g. `name`, `endDate`, `startDate`) fixes that.

2023-01-29 18:01 UTC, studioj commented
awesome @mohit2152sharma  could you also add a test which verifies that functionality

2023-01-29 18:02 UTC, studioj requested changes
Thanks for submitting this.
please add a testcase validating this change

2023-02-04 14:32 UTC, mohit2152sharma commented
I couldn't find test cases for `update_sprint()` function, I was thinking to modify that to include this scenario, could you direct me to the respective section if it exists?

2023-02-28 22:53 UTC, studioj commented
> I couldn't find test cases for `update_sprint()` function, I was thinking to modify that to include this scenario, could you direct me to the respective section if it exists?

maybe have a look here
https://github.com/pycontribs/jira/blob/main/tests/resources/test_sprint.py

2024-03-25 11:47 UTC, adehad commented
Thanks for starting this PR @mohit2152sharma ! We have now merged in a PR that took inspiration from your work #1806

2024-03-25 11:47 UTC, closed without merging