Added warning log if issue link type not present
pycontribs/jira pull request #1787
Opened 2023-12-27 15:36 UTC by SageTheWizard

This error correction created problems for me, resulting in numerous issues to have inverted links (i.e. Blocks / Is Blocked By was inverted). 
Debugging the issue was difficult and required to look into this code to determine what actually happened, if a log message was present, it would have simplified my debugging, so I've added it!

2023-12-27 18:11 UTC, adehad commented on jira/client.py
> +            LOG.warning(
```suggestion
            self.log.warning(
```

We use this logger object !

2023-12-27 18:12 UTC, adehad requested changes
Small change, glad you got it sorted.

2023-12-27 18:36 UTC, studioj commented
master seems ok hopefully lets rebase and see

2023-12-27 18:37 UTC, studioj approved these changes

2023-12-27 18:38 UTC, studioj commented
> Small change, glad you got it sorted.

changes?

2023-12-28 16:44 UTC, SageTheWizard commented
I see there's a failure deploying to the cloud, if this is something caused by my changes please let me know so that I can change as needed.  (I'm doubtful as it's just a log print though :) )

2024-01-01 11:45 UTC, adehad approved these changes
Thanks for this contribution!

2024-01-01 11:45 UTC, merged