project roles: make adding groups work
pycontribs/jira pull request #884
Opened 2019-12-12 21:14 UTC by valentijnscholten

The Role (project role) resource has a method add_user that, according to its documentation and parameters, should be able to add either users or groups to a project role.
The adding of groups was not (yet) implemented. This PR implements that.

Please note that JIRA server only supports either adding users XOR groups in a single request. So I have added a quick check to raise a clear error. The error message from JIRA is some vague 400 error about it being unable to parse the json request.

it's not perfect, but at least the method now works according to its docs.

2021-05-24 14:40 UTC, studioj commented
@valentijnscholten please merge in master, solve conflicts

2021-05-24 16:57 UTC, studioj commented
thx => CI is running, if green it'll get reviewed

codacy is failing atm because of this
https://app.codacy.com/gh/pycontribs/jira/pullRequest?prid=7435647
black is failing on resources.py
https://github.com/pycontribs/jira/pull/884/checks?check_run_id=2657924451#step:8:47

2021-07-10 15:32 UTC, adehad requested changes

2021-07-10 15:32 UTC, adehad commented on jira/resources.py
> +                raise NotImplementedError("JIRA can only add users XOR groups")
```suggestion
        if users is not None: 
            if isinstance(users, str):
                users = (users,)
            data = {"user": users}
            if groups is not None:
                raise NotImplementedError("JIRA can only add users XOR groups")
```

This function accepts both strings and a list/tuple already, so we need to be a bit smarter on the handling here

2021-07-10 15:32 UTC, adehad commented on jira/resources.py
> +            data = {"group": groups}
```suggestion
        if groups is not None:
            if isinstance(groups, str):
                groups = (groups,)
            data = {"group": groups}
```

as above

2023-06-02 21:25 UTC, studioj commented
stale for 4 months => close for now

2023-06-02 21:25 UTC, closed without merging