Improve feedback for oauth errors.
pycontribs/jira pull request #888
Opened 2020-01-03 17:27 UTC by aklajnert

This is a minor improvement with the feedback during the OAuth dance errors.  
I got bitten by it twice, a few months apart and spent some time debugging what's going on. In my case, I got just the `KeyError` exception that the `oauth_token` key does not exist. In my case, the response dict content was as below:
```json
{"oauth_problem": "consumer_key_unknown"}
```

This PR should cause the OAuth dance to return a bit more meaningful error messages during that stage.

2021-05-02 13:39 UTC, adehad commented on jira/jirashell.py
> +        exit(message)
I think raising an error would be preferred here.

2021-05-15 12:17 UTC, ssbarnea approved these changes

2021-05-15 12:44 UTC, adehad commented
@aklajnert if you could merge the latest master and run `tox -e lint`, that should autoformat this correctly for it to be ready to merge.

2021-05-15 12:49 UTC, ssbarnea commented
@adehad Based on my experience many contributors will not bother to fix their older PRs. You can decide to manually implement the same fix yourself if you find it useful and close original PR. Keep in mind to add me as reviewer once it reports green.

2021-05-15 17:06 UTC, ssbarnea requested changes
Please fix CI reported issues

2021-05-16 07:59 UTC, ssbarnea commented
Something is clearly not correct with this change as I see a huge number of reformatted files. It was not correctly rebased from master?

2021-05-16 11:13 UTC, aklajnert commented
> Something is clearly not correct with this change as I see a huge number of reformatted files. It was not correctly rebased from master?

Yeah, sorry - I did struggle with the rebase, and after I did that I had to leave. I've fixed it now.

2021-05-16 15:18 UTC, ssbarnea approved these changes

2021-05-17 07:47 UTC, merged