Added ability to get full list of labels
pycontribs/jira pull request #917
Opened 2020-03-20 07:28 UTC by svermeulen

For issue #913

2021-05-02 13:32 UTC, adehad commented on jira/client.py
> +        url = self._options["server"] + "/rest/api/3/label"
Would transition this to use `self._get_json()`

2021-05-18 13:11 UTC, ssbarnea requested changes
Using print does not seem like ready for review code.

2021-05-24 14:28 UTC, studioj commented
@svermeulen merge in master and resolve conflicts please

2021-10-30 18:07 UTC, studioj commented
@svermeulen any idea if this will be picked up again? => our CI system is working again properly

2021-10-31 14:18 UTC, svermeulen commented
Ok I rebased my branch to latest main, and removed the print statement.  Though I don't know how to address @adehad's comment

2021-10-31 17:56 UTC, adehad requested changes
This endpoint is only available on v3 of the API for Jira Cloud, this needs to be handled correctly.

`self._options["rest_api_version"]` has a value that can be checked against. 

Or we can instead check the `self._is_cloud` value and if true, use a URL with the v3 url?
That would require extension of the `_get_json()` and `_get_url()` methods to accept a version override.


```python
if not self._is_cloud:
    raise NotImplementedError("Only available on Jira Cloud instances.")
if str(self._options["rest_api_version"]) != "3":
    raise NotImplementedError("Needs v3 of the REST API Version.")

```

2021-10-31 18:00 UTC, adehad commented on jira/client.py
> +        url = self._options["server"] + "/rest/api/3/label"
added an example in https://github.com/pycontribs/jira/pull/917#discussion_r739844741

2023-02-07 20:59 UTC, studioj commented
no response after +1yr after requesting changes => close

2023-02-07 20:59 UTC, closed without merging

2023-02-15 12:40 UTC, dvolosnykh commented
Stumbled upon this in 2023. What's left to be done so that the PR goes in?

2023-02-15 17:45 UTC, adehad commented
@dvolosnykh I suggested some changes that were not addressed at the time, if you are able to add them in a new PR that would be ideal.

A test would be greatly appreciated too.